name: Deploy on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest on main branch
        run: git pull
      - name: Rebuild docker-compose 
        run: docker-compose -f docker-compose.dev.yml up --build

