name: Deploy on EC2

on:
  push:
    branches:
      - "no-elastic"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest on main branch
        uses: actions/checkout@v2
        
      - name: Rebuild docker-compose 
        run: sudo docker-compose -f docker-compose.dev.yml up --build

